### ISSUE TITLE
Incomplete steps for usage in README

### ISSUE THREAD

**Issue by ashishk1331** [Digital-Tvilling/react-jsoncanvas#7]
There are no steps written under the heading of Usage. Also, the steps are unclear on how to set up the project.

If possible, please update the README with suitable content.

**Comment by duranbe** [comment]
I've manage to do imports the hacky way, by cloning the repo on the root of my project and use relative import 
`import { Edge } from 'react-jsoncanvas/src'`

**Comment by duranbe** [comment]
But as you can see this repo is more like an experimentation than a real library, eg no tsconfig, no package.json

**Comment by fasblom** [comment]
Hi, thanks for the feedback.

You are correct and this is work in progress as written in the readme. 

That said - PRs are always welcome in case you have working code before us.

**Comment by duranbe** [comment]
Need some more hacks but we are getting somewhere 

```js
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/*.{js,ts,jsx,tsx}",
    "./react-jsoncanvas/src/*.{js,ts,jsx,tsx}",
    "index.html"],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**Comment by duranbe** [comment]
@Teemukoivumaa made a great job finishing the setup, take a look at it @ashishk1331

**Comment by duranbe** [comment]
I've added steps to use locally in https://github.com/Digital-Tvilling/react-jsoncanvas/pull/12
